### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by emejiaa** [mbientlab/PyWarble#5]
hello, can you assist me with the steps required for the installation of this package. I'm rather new to python, but I do have experience with coding (c++). I want to install the metawear python sdk, but I can't seem to set up the correct environment for it's dependencies (PyWarble) as outlined in https://github.com/mbientlab/Warble 

Thus far, I've installed Visual Studio 2017 along with the FCU Windows 10 SDK (10.0.16299.0) (included in desktop development with c++ ) and python, i.e. I selected it from the extra add-on options in the installer.  After creating a python project, I selected view -> other windows -> python environments, and in the window -> packages. I'm able to install common packages, but I get errors when I try to install this one.  The error I get is shown below. I believe I've follow all the instructions shown in the readme. Can you help me figure out how to set up the correct visual studio environment to begin using the metawear package. Thanks! 

----- Installing 'warble' -----
Collecting warble
  Using cached https://files.pythonhosted.org/packages/84/6b/b46e72840edad09c1effc01f20e31eb7e5281ac16415bebfdf267c70c05c/warble-1.1.0.tar.gz
Installing collected packages: warble
  Running setup.py install for warble: started
    Running setup.py install for warble: finished with status 'error'
    Complete output from command "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\eliez\\AppData\\Local\\Temp\\pip-install-d0k_nx3u\\warble\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\eliez\AppData\Local\Temp\pip-record-iqs8d8jg\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Microsoft (R) Build Engine version 4.7.3056.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 10/23/2018 6:39:10 PM.
    Project "C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj" on node 1 (default targets).
    C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj(56,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj" (default target) (1) ->
      C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj(56,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:00.07
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\setup.py", line 93, in <module>
        'Programming Language :: Python :: 3',
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\setup.py", line 50, in run
        raise RuntimeError("Failed to compile warble.dll")
    RuntimeError: Failed to compile warble.dll
    
    ----------------------------------------
Command ""C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\eliez\\AppData\\Local\\Temp\\pip-install-d0k_nx3u\\warble\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\eliez\AppData\Local\Temp\pip-record-iqs8d8jg\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
----- Failed to install 'warble' -----

**Comment by emejiaa** [comment]
I know this isn't a real pywarble issue, but any help would be greatly appreciated.

**Comment by scaryghost** [comment]
Can you build a C++ project from the command line with MSBuild?  Based on the log, it seems like your environment is not properly configured.

```
C:\Users\eliez\AppData\Local\Temp\pip-install-d0k_nx3u\warble\clibs\warble\vs2017\warble.vcxproj(56,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```
